package dotenv

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// WriteEncrypted writes secrets to path with sensitive values AES-GCM encrypted.
// Non-sensitive keys are written as plain text. key must be 32 bytes.
func WriteEncrypted(path string, secrets map[string]string, key []byte) error {
	if len(key) != 32 {
		return fmt.Errorf("encryption key must be 32 bytes, got %d", len(key))
	}

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by vaultpipe — sensitive values are AES-GCM encrypted\n")
	for _, k := range keys {
		v := secrets[k]
		if isSensitive(k) {
			enc, err := Encrypt([]byte(v), key)
			if err != nil {
				return fmt.Errorf("encrypt key %q: %w", k, err)
			}
			sb.WriteString(fmt.Sprintf("%s=enc:%s\n", k, enc))
		} else {
			sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
		}
	}
	return os.WriteFile(path, []byte(sb.String()), 0o600)
}

// ReadEncrypted reads a file written by WriteEncrypted, decrypting enc: prefixed values.
// key must be 32 bytes.
func ReadEncrypted(path string, key []byte) (map[string]string, error) {
	if len(key) != 32 {
		return nil, fmt.Errorf("encryption key must be 32 bytes, got %d", len(key))
	}

	raw, err := Read(path)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(raw))
	for k, v := range raw {
		if strings.HasPrefix(v, "enc:") {
			dec, err := Decrypt(v[4:], key)
			if err != nil {
				return nil, fmt.Errorf("decrypt key %q: %w", k, err)
			}
			out[k] = string(dec)
		} else {
			out[k] = v
		}
	}
	return out, nil
}
