package dotenv

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// GenerateTemplate writes a .env.template file from a secrets map,
// replacing values with empty strings or type hints.
func GenerateTemplate(path string, secrets map[string]string) error {
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Auto-generated by vaultpipe. Do not commit real values.\n")
	for _, k := range keys {
		hint := valueHint(secrets[k])
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, hint))
	}

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// valueHint returns a placeholder hint based on the value's shape.
func valueHint(v string) string {
	if v == "" {
		return ""
	}
	if isNumeric(v) {
		return "<number>"
	}
	if strings.EqualFold(v, "true") || strings.EqualFold(v, "false") {
		return "<bool>"
	}
	return "<string>"
}

func isNumeric(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}
